name: Collect Socials
on:
  push:
  schedule:
    - cron: '0 0 * * *'
jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install tqdm beautifulsoup4
      - name: Search seller ids
        run: python utils/search_scraper.py --query "шапка" --pages 3 --output raw_sellers.csv
      - name: Collect social links
        run: python utils/social_scraper.py --input raw_sellers.csv --output contacts.csv
      - name: Validate contacts
        run: grep -q "@" contacts.csv
