name: WB description test
on:
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      WB_UA: ${{ secrets.WB_UA }}
      WB_COOKIES: ${{ secrets.WB_COOKIES }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install -U pip requests beautifulsoup4
          python test_wb_desc.py
